//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDtoEntities.WinUI.WcfSrvTestDto {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseDTO", Namespace="http://schemas.datacontract.org/2004/07/TestDtoEntities.DTO")]
    [System.SerializableAttribute()]
    public partial class BaseDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idEntityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idEntity {
            get {
                return this.idEntityField;
            }
            set {
                if ((this.idEntityField.Equals(value) != true)) {
                    this.idEntityField = value;
                    this.RaisePropertyChanged("idEntity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfSrvTestDto.IWcfSrvDto")]
    public interface IWcfSrvDto {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfSrvDto/GetListDetalleBloomberg", ReplyAction="http://tempuri.org/IWcfSrvDto/GetListDetalleBloombergResponse")]
        TestDtoEntities.WinUI.WcfSrvTestDto.BaseDTO[] GetListDetalleBloomberg();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfSrvDto/GetListDetalleBloomberg", ReplyAction="http://tempuri.org/IWcfSrvDto/GetListDetalleBloombergResponse")]
        System.Threading.Tasks.Task<TestDtoEntities.WinUI.WcfSrvTestDto.BaseDTO[]> GetListDetalleBloombergAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWcfSrvDtoChannel : TestDtoEntities.WinUI.WcfSrvTestDto.IWcfSrvDto, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WcfSrvDtoClient : System.ServiceModel.ClientBase<TestDtoEntities.WinUI.WcfSrvTestDto.IWcfSrvDto>, TestDtoEntities.WinUI.WcfSrvTestDto.IWcfSrvDto {
        
        public WcfSrvDtoClient() {
        }
        
        public WcfSrvDtoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WcfSrvDtoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WcfSrvDtoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WcfSrvDtoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TestDtoEntities.WinUI.WcfSrvTestDto.BaseDTO[] GetListDetalleBloomberg() {
            return base.Channel.GetListDetalleBloomberg();
        }
        
        public System.Threading.Tasks.Task<TestDtoEntities.WinUI.WcfSrvTestDto.BaseDTO[]> GetListDetalleBloombergAsync() {
            return base.Channel.GetListDetalleBloombergAsync();
        }
    }
}
